# Funding — enables the "Sponsor" button on the repository.
# https://docs.github.com/en/repositories/managing-your-repositories-settings-and-customization/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: xarmian
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# custom: ['https://example.com/sponsor']
