// The census of keyed {#each} blocks in web/src (TASK-3539): every keyed each
// whose key is not its own index names WHY its keys cannot repeat. A repeated
// key throws each_key_duplicate during render, in production builds too, and
// blanks the whole view (BUG-3538). eachKeyCensus.test.ts fails on a keyed each
// with no entry here, and on an entry whose each no longer exists.
//
// An entry is keyed by the file (under web/src) and the each's head,
// whitespace-collapsed: `each <expression> as <item> (<key>)`. A key that is,
// or contains, the each's index variable needs no entry: positions cannot
// repeat.

/** What "unique by construction" must mean for each reason. */
export const EACH_KEY_REASONS = {
	'static-literal': 'the list is a literal in the source (or built only from literals), and its key values were checked distinct',
	'object-or-map-keys': 'the keys come from an object, Map or Set (Object.entries, Object.keys, a SvelteMap), which cannot hold a key twice',
	'db-primary-key': 'the rows come from one server answer keyed by a primary or unique key (or a server dedupe the note names); the client replaces the list, or appends only after checking the id',
	'deduped': 'the list passes through a dedupe on this key before it renders (uniqueBy, uniqueStrings, appendUnique, parseSchema, a Set); the note names it',
	'grouped-by-key': 'the list is built one entry per key (a find-or-create or Map grouping)',
	'position-or-counter': 'the key embeds a position or a counter assigned once per entry',
	'strictly-increasing': 'the key values are generated in strictly increasing order',
} as const;

export type EachKeyReason = keyof typeof EACH_KEY_REASONS;

export const EACH_KEY_CENSUS: Record<string, { reason: EachKeyReason; note: string }> = {
	"lib/components/BacklinksPanel.svelte :: each group.rows as bl, blIdx (rowKey(bl, blIdx))": { reason: 'position-or-counter', note: "rowKey ends with the row's index" },
	"lib/components/BacklinksPanel.svelte :: each groups as group (group.key)": { reason: 'object-or-map-keys', note: "SvelteMap keyed by `ws::collection` (l.121) | Map keys." },
	"lib/components/ChildChart.svelte :: each chartData.yTicks as tick (tick.value)": { reason: 'strictly-increasing', note: "local loop (l.132-139) | `v` rises strictly by `step >= 1`; `total` is pushed only if it is not already last." },
	"lib/components/ChildItems.svelte :: each eligibleCollections as coll (coll.id)": { reason: 'db-primary-key', note: "`collectionStore.collections` filtered | primary key" },
	"lib/components/ChildItems.svelte :: each groupData[laneKey(status)] ?? [] as child, i (child.id)": { reason: 'grouped-by-key', note: "`groupData[laneKey(status)]` | partition of `children` by one status value" },
	"lib/components/ChildItems.svelte :: each groups as [status, _statusChildren] (status)": { reason: 'object-or-map-keys', note: "`groups` | SvelteMap keyed by status; `statusOrder` and leftovers are disjoint" },
	"lib/components/ChildItems.svelte :: each linkCandidates as cand (cand.id)": { reason: 'deduped', note: "`linkResults` from one `api.search` page | server dedupes: FTS excludes ref-hit ids, numeric hits are checked against `alreadySeen` (store/search.go); a single page is never concat" },
	"lib/components/ChildItems.svelte :: each split.reference as child (child.id)": { reason: 'db-primary-key', note: "children from getChildItems (SELECT DISTINCT), partitioned" },
	"lib/components/ChildItems.svelte :: each split.reference as child (child.id) #2": { reason: 'db-primary-key', note: "children from getChildItems (SELECT DISTINCT), partitioned" },
	"lib/components/ChildItems.svelte :: each split.work as child (child.id)": { reason: 'db-primary-key', note: "children from getChildItems (SELECT DISTINCT), partitioned" },
	"lib/components/ConnectWorkspaceModal.svelte :: each MCP_CLIENTS as client (client.id)": { reason: 'static-literal', note: "distinct client ids" },
	"lib/components/ConnectWorkspaceModal.svelte :: each installTabs as tab (tab.id)": { reason: 'static-literal', note: "distinct tab ids" },
	"lib/components/ConnectWorkspaceModal.svelte :: each patClients as client (client.id)": { reason: 'static-literal', note: "distinct client ids" },
	"lib/components/ConnectWorkspaceModal.svelte :: each visibleTabs as tab (tab.id)": { reason: 'static-literal', note: "static `primaryTabs` (l.56), filtered | distinct literal ids mcp/cli/agent." },
	"lib/components/NestedChildren.svelte :: each children as child (child.id)": { reason: 'db-primary-key', note: "`api.items.children` \u2192 `store.getChildItems` (items.go:5307) | `SELECT DISTINCT` over item-1:1 columns collapses the parent and legacy plan link rows for the same edge (the comment" },
	"lib/components/OnboardingLaunchpad.svelte :: each progress as p (p.label)": { reason: 'static-literal', note: "static 3-entry literal | Distinct labels." },
	"lib/components/OnboardingLaunchpad.svelte :: each shortcuts as s, i (s.tool)": { reason: 'static-literal', note: "three distinct tools" },
	"lib/components/OpenChildrenDialog.svelte :: each active.details.open_children as child (child.ref)": { reason: 'db-primary-key', note: "409 `details.open_children` \u2190 `runOpenChildrenGuard` \u2190 `getChildItems` (store/items.go:5313) | `SELECT DISTINCT` collapses a child linked by both `parent` and `implements`. The ref" },
	"lib/components/RelationBacklinksPanel.svelte :: each group.rows as row, i (rowKey(row, i))": { reason: 'position-or-counter', note: "rowKey ends with the row's index" },
	"lib/components/RelationBacklinksPanel.svelte :: each groups as group (group.key)": { reason: 'object-or-map-keys', note: "SvelteMap keyed by `field_key` (l.110) | Map keys." },
	"lib/components/ShareDialog.svelte :: each grants as grant (grant.id)": { reason: 'db-primary-key', note: "grant ids are primary keys (ListCollectionGrants / ListItemGrants); a repeat grant to the same user is refused 409, and a create appends the new grant's freshly minted id" },
	"lib/components/ShareDialog.svelte :: each shareLinks as link (link.id)": { reason: 'db-primary-key', note: "`ListShareLinks` (primary key) plus prepend of a new link | `CreateShareLink` always mints `newID()` (store/share_links.go:53)." },
	"lib/components/activity/EpisodeFeed.svelte :: each earlierEpisodes as ep (ep.key)": { reason: 'position-or-counter', note: "episode key embeds the opening activity id" },
	"lib/components/activity/EpisodeFeed.svelte :: each liveEpisodes as ep (ep.key)": { reason: 'position-or-counter', note: "episode key embeds the opening activity id" },
	"lib/components/admin/UserActivityTab.svelte :: each events as ev (ev.id)": { reason: 'deduped', note: "`ListUserActivity` with keyset paging | Primary key; pages are joined with `appendUnique`." },
	"lib/components/admin/UserModal.svelte :: each TABS as t (t.key)": { reason: 'static-literal', note: "distinct tab keys" },
	"lib/components/admin/UserOverviewTab.svelte :: each recentItems as ev (ev.id)": { reason: 'db-primary-key', note: "one `/admin/users/{id}/activity?limit=20` response, filtered and sliced | Primary key from one SELECT." },
	"lib/components/admin/UserSettingsForm.svelte :: each overrideFields as f (f.key)": { reason: 'static-literal', note: "distinct limit keys" },
	"lib/components/admin/UserWorkspacesTab.svelte :: each visible as ws (ws.workspace_id)": { reason: 'db-primary-key', note: "`GetUserWorkspacesDetailed` | Joined through `workspace_members` PK (workspace_id, user_id) for one user, so each workspace appears once." },
	"lib/components/auth/AuthFooter.svelte :: each cloudLinks as link (link.label)": { reason: 'static-literal', note: "static `allCloudLinks` (l.37) | ten distinct literal labels." },
	"lib/components/auth/AuthHeader.svelte :: each navLinks as link (link.label)": { reason: 'static-literal', note: "`navLinks` | same static literal" },
	"lib/components/auth/AuthHeader.svelte :: each navLinks as link (link.label) #2": { reason: 'static-literal', note: "`navLinks` | same static literal" },
	"lib/components/billing/BillingIntervalPicker.svelte :: each OPTIONS as opt (opt.interval)": { reason: 'static-literal', note: "monthly, annual" },
	"lib/components/charts/BarChart.svelte :: each resolvedSeries as s (s.key)": { reason: 'static-literal', note: "every caller passes a literal series" },
	"lib/components/charts/BarChart.svelte :: each resolvedSeries as s (s.key) #2": { reason: 'static-literal', note: "every caller passes a literal series" },
	"lib/components/charts/layers/AxisY.svelte :: each ticks as tick (tick)": { reason: 'strictly-increasing', note: "d3 `scaleLinear().ticks(4)` (BarChart.svelte:80) | d3 linear ticks are strictly increasing." },
	"lib/components/charts/layers/Bars.svelte :: each series as s (s.key)": { reason: 'static-literal', note: "BarChart `series` props on the insights and print pages | Static literals ('created'/'completed', 'count', 'median_hours')." },
	"lib/components/collections/ArchivedCollections.svelte :: each archived as a (a.id)": { reason: 'db-primary-key', note: "`collections.archived` (store/collections_archive.go) | single SELECT on the collections primary key; removal is only filtering" },
	"lib/components/collections/BoardView.svelte :: each blockedDraftNotices as notice (notice.lane)": { reason: 'object-or-map-keys', note: "`blockedDraftNotices` \u2190 `Object.entries(draftPlacement)` (collection +page.svelte:2598) | Object keys." },
	"lib/components/collections/BoardView.svelte :: each rehomedDrafts as d (d.lane)": { reason: 'object-or-map-keys', note: "`rehomedDrafts` \u2190 `Object.entries(draftPlacement)` | Object keys." },
	"lib/components/collections/BoardView.svelte :: each renderColumns as colValue (colValue)": { reason: 'deduped', note: "uniqueStrings over options with no empty option, plus the UNCATEGORIZED sentinel" },
	"lib/components/collections/BoardView.svelte :: each shown as item, i (item.id)": { reason: 'object-or-map-keys', note: "`columnData` lane \u2190 `localIndex.getByCollection` (stores/localIndex.svelte.ts:1590) | Rows come from a Map keyed by id, and each item is bucketed into exactly one lane." },
	"lib/components/collections/CreateCollectionModal.svelte :: each COLLECTION_TEMPLATES as template (template.id)": { reason: 'static-literal', note: "static `COLLECTION_TEMPLATES` (collection-templates.ts) | Eight distinct literal ids." },
	"lib/components/collections/DisplaySettingsEditor.svelte :: each uniqueBy(selectFieldKeys, (x) => x.key) as f (f.key)": { reason: 'deduped', note: "the list passes through uniqueBy (TASK-3539)" },
	"lib/components/collections/DisplaySettingsEditor.svelte :: each uniqueBy(selectFieldKeys, (x) => x.key) as f (f.key) #2": { reason: 'deduped', note: "the list passes through uniqueBy (TASK-3539)" },
	"lib/components/collections/DisplaySettingsEditor.svelte :: each uniqueBy(sortableFieldKeys, (x) => x.key) as f (f.key)": { reason: 'deduped', note: "the list passes through uniqueBy (TASK-3539)" },
	"lib/components/collections/EditCollectionModal.svelte :: each existingFields as field, i (field.key)": { reason: 'deduped', note: "seeded from parseSchema; the repairs it made are listed (TASK-3539)" },
	"lib/components/collections/FieldEditor.svelte :: each FIELD_TYPES as ft (ft)": { reason: 'static-literal', note: "`FIELD_TYPES` (field-editor-types.ts:69) | static literal with distinct values" },
	"lib/components/collections/FieldEditor.svelte :: each collections as c (c.slug)": { reason: 'db-primary-key', note: "`collectionOptions` from `api.collections.list` (EditCollectionModal:304, CreateCollectionModal:154) | `UNIQUE(workspace_id, slug)`" },
	"lib/components/collections/FilterBar.svelte :: each Object.entries(relationLabels) as [id, label] (id)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"lib/components/collections/FilterBar.svelte :: each Object.entries(relationLabels) as [id, label] (id) #2": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"lib/components/collections/FilterBar.svelte :: each relationFields as rf (rf.key)": { reason: 'deduped', note: "parseSchema fields" },
	"lib/components/collections/FilterBar.svelte :: each statusOptions as option (option)": { reason: 'deduped', note: "parseSchema options" },
	"lib/components/collections/ItemActionsMenu.svelte :: each actions as a (a.dir)": { reason: 'static-literal', note: "`VERTICAL_ACTIONS` + `HORIZONTAL_ACTIONS` | static literal with distinct `dir` values" },
	"lib/components/collections/LaneActionsMenu.svelte :: each laneTags as t (t)": { reason: 'deduped', note: "`laneTags` | Set, then sorted (:109)." },
	"lib/components/collections/LaneActionsMenu.svelte :: each members as m (m.user_id)": { reason: 'db-primary-key', note: "page `workspaceMembers` \u2190 members API | `workspace_members` primary key." },
	"lib/components/collections/LaneActionsMenu.svelte :: each moveTargets as target (target)": { reason: 'deduped', note: "parseSchema options" },
	"lib/components/collections/LaneActionsMenu.svelte :: each priorityOptions as p (p)": { reason: 'deduped', note: "parseSchema options" },
	"lib/components/collections/LaneActionsMenu.svelte :: each sortOptions as opt (opt.value)": { reason: 'static-literal', note: "`SORT_OPTIONS` (lib/collections/itemSort.ts:12), filtered | Static literal with distinct values." },
	"lib/components/collections/LaneActionsMenu.svelte :: each tagSuggestions as t (t)": { reason: 'object-or-map-keys', note: "`tagSuggestions` \u2190 `tagCounts` (collection +page.svelte:1889) | Map keys." },
	"lib/components/collections/ListView.svelte :: each groupItems as group (group.id)": { reason: 'deduped', note: "uniqueStrings options without empty, extras deduped by a Set, the empty lane once" },
	"lib/components/collections/ListView.svelte :: each grpItems as item, i (item.id)": { reason: 'grouped-by-key', note: "`groupData[laneKey(g)]` from `propGroupData` | each item is bucketed once by `groupValueFor`; with duplicate options both groups render the same bucket, but within one list the ids" },
	"lib/components/collections/QuickActionsEditor.svelte :: each collectionActions as { action, index } (index)": { reason: 'position-or-counter', note: "the original array index" },
	"lib/components/collections/QuickActionsEditor.svelte :: each itemActions as { action, index } (index)": { reason: 'position-or-counter', note: "the original array index" },
	"lib/components/collections/StatusPicker.svelte :: each optionList as option (option)": { reason: 'deduped', note: "uniqueStrings" },
	"lib/components/collections/TableView.svelte :: each sortedItems as item, i (item.id)": { reason: 'object-or-map-keys', note: "`items` = `localIndex.getByCollection` (SvelteMap keyed by item id), then filtered and sorted | Map values; nothing concatenates them" },
	"lib/components/collections/TableView.svelte :: each visibleFields as field (field.key)": { reason: 'deduped', note: "parseSchema" },
	"lib/components/collections/TableView.svelte :: each visibleFields as field (field.key) #2": { reason: 'deduped', note: "parseSchema" },
	"lib/components/collections/TagFilter.svelte :: each tags as { tag, count } (tag)": { reason: 'object-or-map-keys', note: "`tagCounts` ([collection]/+page.svelte:1889) | Map keys, built from `parseTags`, which keeps strings only." },
	"lib/components/common/EmojiPicker.svelte :: each EMOJI_GROUPS as group (group.label)": { reason: 'static-literal', note: "distinct group labels" },
	"lib/components/common/EmojiPicker.svelte :: each group.emojis as emoji (emoji)": { reason: 'static-literal', note: "each group has 12 distinct emoji" },
	"lib/components/common/KeyboardShortcuts.svelte :: each group.shortcuts as shortcut (shortcut.description)": { reason: 'static-literal', note: "descriptions distinct within each group (checked)" },
	"lib/components/common/KeyboardShortcuts.svelte :: each groups as group (group.title)": { reason: 'static-literal', note: "distinct group titles" },
	"lib/components/common/Lightbox.svelte :: each toolbarActions as action (action.id)": { reason: 'static-literal', note: "`ATTACHMENT_ACTIONS.filter` (attachments/actions.ts:172) | static literal ids open/download/copy-link/delete." },
	"lib/components/common/NotificationPanel.svelte :: each toastStore.history as entry (entry.id)": { reason: 'position-or-counter', note: "toast ids carry a counter" },
	"lib/components/common/ToastContainer.svelte :: each errors as toast (toast.id)": { reason: 'position-or-counter', note: "toast ids carry a counter" },
	"lib/components/common/ToastContainer.svelte :: each others as toast (toast.id)": { reason: 'position-or-counter', note: "toast ids carry a counter" },
	"lib/components/editor/Editor.svelte :: each getFilteredLinks() as doc, i (doc.id)": { reason: 'object-or-map-keys', note: "`localIndex.getAll` | SvelteMap keyed by item id; the list is only filtered and sliced." },
	"lib/components/editor/EditorBubbleMenu.svelte :: each sortedCollections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list" },
	"lib/components/fields/FieldEditor.svelte :: each multiChoices as option, i (option)": { reason: 'deduped', note: "uniqueStrings" },
	"lib/components/fields/FieldEditor.svelte :: each optionList as option, i (option)": { reason: 'deduped', note: "uniqueStrings" },
	"lib/components/fields/TagInput.svelte :: each filteredSuggestions as s, i (s)": { reason: 'deduped', note: "uniqueStrings over the suggestions" },
	"lib/components/graph/ItemGraph.svelte :: each [1, 2, 3, 4, 5] as d (d)": { reason: 'static-literal', note: "five distinct numbers" },
	"lib/components/graph/ItemGraph.svelte :: each legend as entry (entry.slug)": { reason: 'object-or-map-keys', note: "`Object.entries(palette.colors)` (l.219) | object keys." },
	"lib/components/graph/ItemGraph.svelte :: each visibleEdges as e (e.source + '->' + e.target + ':' + e.type)": { reason: 'deduped', note: "`renderEdges` \u2190 `ListWorkspaceGraphLinks` | Deduped on (source_id, target_id, type) after type normalization (store/graph.go dedupe block), and ids map 1:1 to refs." },
	"lib/components/graph/ItemGraph.svelte :: each visibleNodes as n (n.ref)": { reason: 'db-primary-key', note: "`renderNodes` \u2190 graph handler nodes (handlers_graph.go:273) | One per item row, with empty refs skipped. A ref's number is unique per workspace (allocated MAX+1 under the per-works" },
	"lib/components/items/BuiltinUpdateNotice.svelte :: each fieldChanges as change (change.key)": { reason: 'deduped', note: "`builtinFieldChanges` (lib/library/builtinOffers.ts:82) | iterates a Set of keys" },
	"lib/components/items/CopyItemDialog.svelte :: each destCollections as c (c.slug)": { reason: 'db-primary-key', note: "`api.collections.list` filtered | `UNIQUE(workspace_id, slug)`" },
	"lib/components/items/CopyItemDialog.svelte :: each linkRows as r (r.dir + r.type)": { reason: 'object-or-map-keys', note: "`linkRows` from `Object.entries(outgoing_links)` + `Object.entries(incoming_links)` | object keys are unique per direction; the 'outgoing'/'incoming' prefixes make dir+type unique" },
	"lib/components/items/CopyItemDialog.svelte :: each overrideRows as row (row.key)": { reason: 'object-or-map-keys', note: "`overrideRows` via `mergeOverrideRows` | rebuilt from a Map keyed by key (line 721)" },
	"lib/components/items/CopyItemDialog.svelte :: each preflight.fields.dropped as f (f.key + f.kind)": { reason: 'deduped', note: "`preflight.fields.dropped` | field rows go through `sortedDroppedKeys`, which dedupes with `seen` (handlers_items_copy_preflight.go:1544); the two assignment rows have fixed keys;" },
	"lib/components/items/CopyItemDialog.svelte :: each workspaces as ws (ws.slug)": { reason: 'db-primary-key', note: "`api.workspaces.list` (`GetUserWorkspaces`) | `workspace_members` has `PRIMARY KEY(workspace_id, user_id)`; slug is globally unique" },
	"lib/components/items/DecisionChips.svelte :: each chips as chip (chip.key)": { reason: 'deduped', note: "`attentionChips` keyed by question_key, same query | one row per (set, key), and only the `attention` set is kept." },
	"lib/components/items/DecisionChips.svelte :: each convChips as chip (chip.ref)": { reason: 'deduped', note: "`conventionChips(res.decisions)` \u2190 `store.LatestItemDecisions` (decisions.go:413) | the NOT EXISTS picks the latest row per (set, question_key) with an id tiebreak; ref = question_" },
	"lib/components/items/ItemAppActions.svelte :: each actions as a (keyOf(a))": { reason: 'db-primary-key', note: "UNIQUE (install_id, action_key)" },
	"lib/components/items/ItemAttachmentStrip.svelte :: each visible as att (att.id)": { reason: 'db-primary-key', note: "server page merged with `pendingUploads` | `missed` excludes ids already in the page (:477/:695); the upload listener and delete rollback check `some(id)` before inserting (:859, :" },
	"lib/components/items/ItemDetail.svelte :: each LINK_DIRECTIONS as d (d.value)": { reason: 'static-literal', note: "static `LINK_DIRECTIONS` (lib/items/linkDirections.ts:27-37) | 11 distinct literal values." },
	"lib/components/items/ItemDetail.svelte :: each PANE_TABS as t (t.id)": { reason: 'static-literal', note: "distinct tab ids" },
	"lib/components/items/ItemDetail.svelte :: each agentRoles as role (role.id)": { reason: 'db-primary-key', note: "`api.agentRoles.list` | Primary key id from one SELECT." },
	"lib/components/items/ItemDetail.svelte :: each group.entries as entry (entry.key)": { reason: 'db-primary-key', note: "link id plus direction; the create append checks the id first" },
	"lib/components/items/ItemDetail.svelte :: each item.moved_to as dest (dest.workspace_slug + '/' + dest.item_slug)": { reason: 'db-primary-key', note: "`movedToDestinations` (server/item_moved_to.go:188) | One live target item per move row (uq_item_workspace_moves_target); workspace slug is globally UNIQUE and items are UNIQUE(wor" },
	"lib/components/items/ItemDetail.svelte :: each moveTargets as target (target.slug)": { reason: 'db-primary-key', note: "`collectionStore.collections` filtered | One list response per workspace, UNIQUE(workspace_id, slug)." },
	"lib/components/items/ItemDetail.svelte :: each relationshipGroups as group (group.label)": { reason: 'object-or-map-keys', note: "`buildRelationshipGroups` (ItemDetail.svelte:5309) | Groups are built in a Map by group key, and the 13 definition labels are distinct static strings." },
	"lib/components/items/ItemDetail.svelte :: each schema.fields as field (field.key)": { reason: 'deduped', note: "parseSchema" },
	"lib/components/items/ItemDetail.svelte :: each workspaceMembers as member (member.user_id)": { reason: 'db-primary-key', note: "`ListWorkspaceMembers` | `workspace_members` PRIMARY KEY (workspace_id, user_id)." },
	"lib/components/items/ItemPicker.svelte :: each options as option, i (option.id)": { reason: 'deduped', note: "`options` = `present(rawResults)` + a sentinel create row | all three sources are unique: warm (MiniSearch returns each doc once; the hoisted ref is removed from `out`), recent (lo" },
	"lib/components/items/PushToAgentDialog.svelte :: each acceptingSessions as session (session.id)": { reason: 'db-primary-key', note: "session presence keyed by session id" },
	"lib/components/items/PushToAgentDialog.svelte :: each acceptingSessions as session (session.id) #2": { reason: 'db-primary-key', note: "session presence keyed by session id" },
	"lib/components/layout/CreateWorkspaceModal.svelte :: each group.templates as tpl (tpl.name)": { reason: 'static-literal', note: "`/templates` \u2192 `collections.ListTemplates` (static `templates` slice, templates.go:634) | static registry with distinct names (startup, scrum, product, blank, demo, hiring, intervi" },
	"lib/components/layout/CreateWorkspaceModal.svelte :: each grouped as group (group.category)": { reason: 'object-or-map-keys', note: "`groupTemplatesByCategory` (utils/templates.ts:42) | a Map by category, and each CATEGORY_ORDER entry is deleted from the map once emitted." },
	"lib/components/layout/PendingInvitations.svelte :: each invitations as inv (inv.id)": { reason: 'db-primary-key', note: "`pendingInvitations.invitations` \u2190 `/me/invitations` (store/my_invitations.go) | invitation primary key with 1:1 joins; list replaced whole or filtered" },
	"lib/components/layout/QuickCaptureSheet.svelte :: each collections as c (c.id)": { reason: 'db-primary-key', note: "`collectionStore.collections` filtered | primary key" },
	"lib/components/layout/RecentlyDeletedWorkspaces.svelte :: each deleted as ws (ws.slug)": { reason: 'db-primary-key', note: "`api.workspaces.listDeleted` | single-table workspaces rows, and `slug` is globally `UNIQUE` (001_initial.sql, pg 001), soft-deleted rows included." },
	"lib/components/layout/Sidebar.svelte :: each agentCollections as collection (collection.id)": { reason: 'db-primary-key', note: "collections list" },
	"lib/components/layout/Sidebar.svelte :: each pickerCollections as coll, i (coll.id)": { reason: 'db-primary-key', note: "collections list" },
	"lib/components/layout/Sidebar.svelte :: each sidebarCollections as collection (collection.id)": { reason: 'db-primary-key', note: "collections list (GROUP BY c.id), replaced whole; a drag swaps an entry for its shadow" },
	"lib/components/layout/TopBar.svelte :: each dndTabs as tab, i (tab.id)": { reason: 'db-primary-key', note: "`tabsStore.tabs` (server answers only) \u2190 `user_workspace_tabs` | PRIMARY KEY(user_id, workspace_id); the id is the slug, which is globally unique; the store never builds tabs local" },
	"lib/components/layout/UserMenuResources.svelte :: each links as link (link.label)": { reason: 'static-literal', note: "static `cloudLinks` / `selfHostedLinks` | Distinct labels in each list." },
	"lib/components/layout/WorkspaceDiscovery.svelte :: each options as option, i (option.kind === 'workspace' ? option.ws.slug : '__create')": { reason: 'db-primary-key', note: "workspace slugs are globally unique; the store create append checks the id first" },
	"lib/components/layout/WorkspaceSheet.svelte :: each agentCollections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list" },
	"lib/components/layout/WorkspaceSheet.svelte :: each navDestinations as dest (dest.key)": { reason: 'static-literal', note: "`getPrimaryDestinations` (nav/destinations.ts:61) | static literal with distinct keys." },
	"lib/components/layout/WorkspaceSheet.svelte :: each regularCollections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list (GROUP BY c.id), filtered" },
	"lib/components/layout/WorkspaceSwitcher.svelte :: each otherWorkspaces as ws (ws.slug)": { reason: 'db-primary-key', note: "a filter of workspaceStore.workspaces" },
	"lib/components/layout/WorkspaceSwitcher.svelte :: each tabsStore.tabs as tab (tab.slug)": { reason: 'db-primary-key', note: "`tabsStore.tabs` \u2190 `/me/workspace-tabs` | `user_workspace_tabs` PRIMARY KEY (user_id, workspace_id), globally unique slugs, list replaced wholesale." },
	"lib/components/layout/WorkspaceSwitcher.svelte :: each workspaceStore.workspaces as ws (ws.slug)": { reason: 'db-primary-key', note: "workspace slugs are globally unique; the store create append checks the id first" },
	"lib/components/playbooks/PlaybookFormFields.svelte :: each PLAYBOOK_ARGUMENT_TYPES as t (t)": { reason: 'static-literal', note: "`PLAYBOOK_ARGUMENT_TYPES` (arguments.ts:28) | static literal with five distinct values." },
	"lib/components/playbooks/PlaybookFormFields.svelte :: each uniqueStrings(arg.enum) as opt (opt)": { reason: 'deduped', note: "the list passes through uniqueStrings (TASK-3539)" },
	"lib/components/playbooks/PlaybookFormFields.svelte :: each uniqueStrings(scopes) as s (s)": { reason: 'deduped', note: "the list passes through uniqueStrings (TASK-3539)" },
	"lib/components/playbooks/PlaybookFormFields.svelte :: each uniqueStrings(statuses) as st (st)": { reason: 'deduped', note: "the list passes through uniqueStrings (TASK-3539)" },
	"lib/components/playbooks/PlaybookFormFields.svelte :: each uniqueStrings(triggers) as t (t)": { reason: 'deduped', note: "the list passes through uniqueStrings (TASK-3539)" },
	"lib/components/search/CommandPalette.svelte :: each Object.entries(facets.collections) as [slug, count] (slug)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"lib/components/search/CommandPalette.svelte :: each Object.entries(facets.statuses) as [status, count] (status)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"lib/components/search/CommandPalette.svelte :: each Object.entries(groupedResults) as [slug, group] (slug)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"lib/components/search/CommandPalette.svelte :: each contentResults as r, i (r.item.id || r.item.slug)": { reason: 'deduped', note: "`contentResults` from one server page, filtered against `results` | one deduped server page; never appended to" },
	"lib/components/search/CommandPalette.svelte :: each group.results as r (r.item.id || r.item.slug)": { reason: 'deduped', note: "results; Load more appends through uniqueBy on the item id" },
	"lib/components/search/CommandPalette.svelte :: each recentSearches as recent, i (recent)": { reason: 'deduped', note: "`recentSearches` from localStorage | the only writer, `saveRecentSearch` (line 884), always dedupes before writing (and has since it was added). Caveat: `loadRecentSearches` does n" },
	"lib/components/search/CommandPalette.svelte :: each results as r, i (r.item.id || r.item.slug)": { reason: 'deduped', note: "Load more appends through uniqueBy on the item id" },
	"lib/components/settings/StorageTab.svelte :: each attachments as att (att.id)": { reason: 'db-primary-key', note: "`WorkspaceAttachments` page, replaced per page (not appended) | Primary key; the LEFT JOIN to items is 1:1." },
	"lib/components/settings/StorageTab.svelte :: each collections as coll (coll.id)": { reason: 'db-primary-key', note: "settings page `api.collections.list` | Primary key from a single SELECT." },
	"lib/components/settings/apps/AppArtifactReview.svelte :: each artifact.changes as ch (ch)": { reason: 'db-primary-key', note: "`norm.Warnings` \u2190 `preprocessArtifactFields` (handlers_artifact_import.go:249) | Each warning names its own field key. The first hit clears the value, so a repeated schema key can'" },
	"lib/components/settings/apps/AppDraftsPanel.svelte :: each artifacts as a (a.item_id)": { reason: 'db-primary-key', note: "`appInstallArtifacts` \u2190 `ListInstallArtifactItems` (app_lifecycle.go:472) | Single SELECT of item ids." },
	"lib/components/settings/apps/AppInstallDetail.svelte :: each actions as a (a)": { reason: 'static-literal', note: "`actions` switch | static literal arrays with distinct values" },
	"lib/components/settings/apps/AppInstallFlow.svelte :: each preview.artifacts as a (a.key)": { reason: 'db-primary-key', note: "`CompanionPack.Artifacts` | manifest.go:278 refuses a repeated artifact key." },
	"lib/components/settings/apps/AppInstallFlow.svelte :: each preview.collections as c (c.key)": { reason: 'db-primary-key', note: "`preview.collections` \u2190 `CompanionPack.Collections` | appmanifest/manifest.go:243 refuses a repeated collection key." },
	"lib/components/settings/apps/AppInstallFlow.svelte :: each preview.item_actions as act (act.key)": { reason: 'db-primary-key', note: "`m.ItemActions` | manifest.go:322 refuses a repeated action key." },
	"lib/components/settings/apps/AppUpgradeReview.svelte :: each automatic as e (e.kind + e.key + e.change)": { reason: 'object-or-map-keys', note: "`diff` class\u2260review | auto entries come only from map-keyed loops (events, item_actions, released collections, removed artifacts) and the fixed service/delegated access pair." },
	"lib/components/settings/apps/AppUpgradeReview.svelte :: each newDrafts as a (a.key)": { reason: 'deduped', note: "`preview.artifacts`, filtered by a key Set | manifest artifact keys are validated unique (manifest.go:278)." },
	"lib/components/settings/apps/AppUpgradeReview.svelte :: each result.items as it (it.key)": { reason: 'db-primary-key', note: "confirm `items` (handlers_apps_upgrade.go:255), key = `plan.Artifacts[i].Key` | artifact keys are refused if duplicated at manifest parse (appmanifest/manifest.go:278)." },
	"lib/components/settings/apps/AppsTab.svelte :: each live as app (app.install_id)": { reason: 'db-primary-key', note: "`ListWorkspaceInstalls` (app_lifecycle.go:428) | Primary key; the LEFT JOIN to users is by id, so 1:1." },
	"lib/components/settings/apps/AppsTab.svelte :: each tombstones as app (app.install_id)": { reason: 'db-primary-key', note: "same | Primary key." },
	"lib/components/share/PublicBoardView.svelte :: each column.items as item (item.key)": { reason: 'position-or-counter', note: "key is ref#payload-index, assigned at parse" },
	"lib/components/share/PublicBoardView.svelte :: each columns as column (column.value)": { reason: 'deduped', note: "`groupItems` (shareView.ts:442) | the final order is deduped through a `Set` (l.476-481), so even duplicate schema options collapse." },
	"lib/components/share/PublicFieldChips.svelte :: each chips as { field, text, placeholder, color } (field.key)": { reason: 'deduped', note: "fieldChips over visibleFields, normalised like parseSchema" },
	"lib/components/share/PublicListView.svelte :: each group.items as item (item.key)": { reason: 'position-or-counter', note: "key is ref#payload-index, assigned at parse" },
	"lib/components/share/PublicListView.svelte :: each groups as group (group.value)": { reason: 'deduped', note: "`groupItems` (share/shareView.ts:442) | Group values are deduped by a Set at shareView.ts:476, which also absorbs repeated schema options." },
	"lib/components/share/PublicTableView.svelte :: each columns as field (field.key)": { reason: 'deduped', note: "visibleFields, normalised like parseSchema" },
	"lib/components/share/PublicTableView.svelte :: each columns as field (field.key) #2": { reason: 'deduped', note: "visibleFields, normalised like parseSchema" },
	"lib/components/share/PublicTableView.svelte :: each items as item (item.key)": { reason: 'position-or-counter', note: "key is ref#payload-index, assigned at parse" },
	"lib/components/timeline/HistoryView.svelte :: each FILTERS as f (f.id)": { reason: 'static-literal', note: "distinct filter ids" },
	"lib/components/timeline/HistoryView.svelte :: each ev.changes as c (c.field)": { reason: 'grouped-by-key', note: "merged per field before push" },
	"lib/components/timeline/HistoryView.svelte :: each ev.decisions as d (d.id)": { reason: 'db-primary-key', note: "timeline entry ids, deduped by usedIDs" },
	"lib/components/timeline/HistoryView.svelte :: each ev.notes as n (n.id)": { reason: 'deduped', note: "`ev.notes` | Entry ids deduped by `usedIDs` with a positional fallback." },
	"lib/components/timeline/HistoryView.svelte :: each ev.versions as v (v.id)": { reason: 'db-primary-key', note: "`ev.versions` | Distinct timeline entries (version primary keys)." },
	"lib/components/timeline/HistoryView.svelte :: each people as p (p)": { reason: 'deduped', note: "`peopleOf` (timeline/historyEvents.ts:371) | Deduped with `includes` before push." },
	"lib/components/timeline/HistoryView.svelte :: each shown as row, i (row.id)": { reason: 'deduped', note: "`groupHistory(timelineFeed.entries)` | A row id is one of its entries' ids. Entries are unique: the server's `entryID` uses a `usedIDs` guard (server/handlers_timeline.go:399), and" },
	"lib/components/timeline/ReactionPicker.svelte :: each EMOJIS as emoji (emoji)": { reason: 'static-literal', note: "12 distinct emoji" },
	"lib/components/timeline/TimelineCommentCard.svelte :: each comment.replies as reply (reply.id)": { reason: 'db-primary-key', note: "`comment.replies` built server-side (handlers_timeline.go:536) | from a single comments SELECT by PK (the joins are 1:1 by id); the client never edits replies." },
	"lib/components/timeline/TimelineCommentCard.svelte :: each list as chip (chip.ref)": { reason: 'db-primary-key', note: "`commentChipsStore.chipsFor` \u2190 `commentConventionChips` \u2190 `LatestItemDecisions` | one row per question_key `conv:REF@commentId`, so one ref per comment." },
	"lib/components/timeline/TimelineCommentCard.svelte :: each reactionGroups as group (group.emoji)": { reason: 'object-or-map-keys', note: "`groupReactions` (l.131) | Map keyed by emoji." },
	"lib/components/timeline/TimelineCommentCard.svelte :: each replyReactionGroups as group (group.emoji)": { reason: 'object-or-map-keys', note: "`groupReactions` | Map keys." },
	"lib/components/timeline/TimelineEntryList.svelte :: each entries as entry (entry.id)": { reason: 'deduped', note: "ItemTimeline `entries` \u2190 `buildTimeline` | The comment, activity and version ids are each a DB PK from a single-table query. Notes and decisions are deduped through `usedIDs` (hand" },
	"lib/components/versions/DiffView.svelte :: each entry.lines as innerLine (`${idx}-${innerLine.oldLineNum ?? 'n'}-${innerLine.newLineNum ?? 'n'}-${innerLine.type}`)": { reason: 'strictly-increasing', note: "`buildDiffLines` (DiffView.svelte:46) | Line numbers come from counters that only go up. Added lines carry a unique new number, removed lines a unique old number, unchanged lines a" },
	"routes/[username]/[workspace]/+page.svelte :: each Object.entries(breakdown) as [status, count] (status)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"routes/[username]/[workspace]/+page.svelte :: each collections as coll (coll.slug)": { reason: 'db-primary-key', note: "`api.collections.list` \u2190 `ListCollections` (handlers_collections.go:72) | Single SELECT, only filtered afterwards; collections have UNIQUE(workspace_id, slug)." },
	"routes/[username]/[workspace]/+page.svelte :: each dashboard.active_items as item (item.slug)": { reason: 'db-primary-key', note: "`dashboard.active_items` \u2190 one `ListItems` (handlers_dashboard.go:498, 553-576) | One entry per row of a single SELECT whose joins are 1:1; items have UNIQUE(workspace_id, slug)." },
	"routes/[username]/[workspace]/+page.svelte :: each dashboard.starred_items as item (item.slug)": { reason: 'db-primary-key', note: "`dashboard.starred_items` \u2190 `ListStarredItems` (item_stars.go:96) | `item_stars` has PRIMARY KEY(user_id, item_id) and the query filters to one user, so one row per item." },
	"routes/[username]/[workspace]/+page.svelte :: each visibleRows(attentionOrdered, ATTENTION_CAP, attentionExpanded) as alert (`${alert.type}:${alert.item_slug}`)": { reason: 'db-primary-key', note: "`dashboard.attention` (handlers_dashboard.go:680-930), reordered by `orderAttention` | The key is type plus slug, and each type is emitted at most once per item. \"Stalled\" checks t" },
	"routes/[username]/[workspace]/+page.svelte :: each visibleRows(dashboard.active_plans, PLANS_CAP, plansExpanded) as plan (plan.slug)": { reason: 'db-primary-key', note: "`dashboard.active_plans` \u2190 one `ListItems(CollectionSlug:\"plans\")` (handlers_dashboard.go:590-670) | One DashboardPlan per row of a single SELECT; item slugs are unique per workspa" },
	"routes/[username]/[workspace]/[collection]/+page.svelte :: each VIEW_CHOICES as choice (choice.mode)": { reason: 'static-literal', note: "three distinct modes" },
	"routes/[username]/[workspace]/[collection]/+page.svelte :: each blockedDraftNotices as notice (notice.lane)": { reason: 'object-or-map-keys', note: "`blockedDraftNotices` from `Object.entries(draftPlacement)` (`draftTargets`, laneDrafts.ts:219) | object keys are unique" },
	"routes/[username]/[workspace]/[collection]/+page.svelte :: each savedViews as view (view.id)": { reason: 'db-primary-key', note: "views PK; the create append checks the id first" },
	"routes/[username]/[workspace]/[collection]/+page.svelte :: each sortOptions as opt (opt.value)": { reason: 'static-literal', note: "`SORT_OPTIONS` (lib/collections/itemSort.ts:12), optionally filtered | static literal with five distinct values" },
	"routes/[username]/[workspace]/activity/+page.svelte :: each ACTOR_OPTIONS as opt (opt.value)": { reason: 'static-literal', note: "static `ACTOR_OPTIONS` (lib/activity/activityFilters.ts:19) | Literal list with three distinct values: '', 'user', 'agent'." },
	"routes/[username]/[workspace]/activity/+page.svelte :: each collections as coll (coll.id)": { reason: 'db-primary-key', note: "`api.collections.list` \u2192 `store.ListCollections` | DB primary key from a single SELECT of live collections." },
	"routes/[username]/[workspace]/activity/+page.svelte :: each group.items as activity (activity.id)": { reason: 'deduped', note: "`group.items` \u2190 `activities` | Primary key from one SELECT; `appendUnique` (activityPaging.ts:41, a Set of ids) and `mergeHead` (a Map by id) dedupe later pages and head refreshes;" },
	"routes/[username]/[workspace]/activity/+page.svelte :: each groupedActivities as group (group.date)": { reason: 'grouped-by-key', note: "`groupedActivities` $derived over `activities` | A new group starts only when the day changes from the previous row. That gives unique dates because the list is kept sorted: the se" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each CATEGORIES as category (category)": { reason: 'static-literal', note: "distinct categories" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each ENFORCEMENT_LEVELS as p (p)": { reason: 'static-literal', note: "three distinct levels" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each ENFORCEMENT_LEVELS as p (p) #2": { reason: 'static-literal', note: "three distinct levels" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each allSurfaces as s (s)": { reason: 'deduped', note: "parseSchema options plus a Set of item surfaces" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each createSurfaces as s (s)": { reason: 'deduped', note: "schema options via parseSchema" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each createTriggers as t (t)": { reason: 'deduped', note: "schema options via parseSchema (static fallback is distinct)" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each group.items as item (item.id)": { reason: 'db-primary-key', note: "item ids; the create append checks the id first" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each grouped as group (group.trigger)": { reason: 'deduped', note: "order list is parseSchema options plus extras deduped by a Set" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each uniqueStrings(convention.commands) as command (command)": { reason: 'deduped', note: "the list passes through uniqueStrings (TASK-3539)" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each withCurrent(ENFORCEMENT_LEVELS, editMetaBase.enforcement) as lv (lv)": { reason: 'static-literal', note: "`withCurrent(ENFORCEMENT_LEVELS, \u2026)` | Static three-value literal; the current value is added only when absent." },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each withCurrent(createSurfaces, editMetaBase.surface) as sv (sv)": { reason: 'deduped', note: "schema options via parseSchema" },
	"routes/[username]/[workspace]/conventions/+page.svelte :: each withCurrent(createTriggers, editMetaBase.trigger) as t (t)": { reason: 'deduped', note: "schema options via parseSchema (static fallback is distinct)" },
	"routes/[username]/[workspace]/graph/DetailCard.svelte :: each shownBlockers as b (b.ref)": { reason: 'deduped', note: "prop `blockedBy` \u2190 `directBlockers()` (graph/+page.svelte:825) | Deduped by a `seen` Set on `e.source` at graph/+page.svelte:830-834." },
	"routes/[username]/[workspace]/graph/GraphToolbar.svelte :: each collections as slug (slug)": { reason: 'deduped', note: "`distinctCollections` (graph/+page.svelte:175) | deduped with a Set" },
	"routes/[username]/[workspace]/graph/GraphToolbar.svelte :: each matches as m, i (m.ref)": { reason: 'db-primary-key', note: "`matches` \u2282 `searchNodes` = `filteredData.nodes` (handlers_graph.go) | nodes are built once per included item id; ref is unique per workspace via `idx_items_workspace_number`" },
	"routes/[username]/[workspace]/graph/GraphToolbar.svelte :: each roles as role (role)": { reason: 'deduped', note: "`distinctRoles` (graph/+page.svelte:197) | deduped with a Set" },
	"routes/[username]/[workspace]/graph/GraphToolbar.svelte :: each statuses as status (status)": { reason: 'deduped', note: "`distinctStatuses` (graph/+page.svelte:186) | deduped with a Set" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each CARD_OPTIONS as card (card.id)": { reason: 'static-literal', note: "distinct card ids" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each WINDOW_OPTIONS as opt (opt.value)": { reason: 'static-literal', note: "distinct window values" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each group.items as item (item.ref)": { reason: 'db-primary-key', note: "completed_items GROUP BY i.id; ref is unique per workspace" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each group.rows as row (row.status)": { reason: 'object-or-map-keys', note: "`status_distribution` (`reportStatusDistribution` / `reportSnapshotAsOf`) | per collection: `GROUP BY LOWER(...)` on the live path, Go map keys on the past-period path" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each pickableCollections as coll (coll.id)": { reason: 'db-primary-key', note: "`collections` from `api.collections.list` (store `ListCollections`) | collection id is the primary key, one row per collection" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each report.cycle_time.by_collection as row (row.collection)": { reason: 'object-or-map-keys', note: "`report.cycle_time.by_collection` (store `reportCycleTime` \u2192 `durationsByCollection`) | one row per key of a Go map keyed by collection id, then mapped to slug; `UNIQUE(workspace_i" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each report.wip.by_collection as row (row.collection)": { reason: 'object-or-map-keys', note: "`report.wip.by_collection` (`reportWIP` / `reportSnapshotAsOf` \u2192 `durationsByCollection`) | same map-by-collection-id construction; `resolveReportCollections` yields each collectio" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each shippedGroups as group (group.collection)": { reason: 'grouped-by-key', note: "`shippedGroups` $derived over `report.completed_items` | grouped with find-or-create on `collection`, so one group per slug" },
	"routes/[username]/[workspace]/insights/+page.svelte :: each statusByCollection as group (group.collection)": { reason: 'grouped-by-key', note: "`statusByCollection` $derived over `report.status_distribution` | grouped with find-or-create on `collection`" },
	"routes/[username]/[workspace]/insights/print/+page.svelte :: each group.items as item (item.ref)": { reason: 'db-primary-key', note: "completed_items GROUP BY i.id; ref is unique per workspace" },
	"routes/[username]/[workspace]/insights/print/+page.svelte :: each group.rows as row (row.status)": { reason: 'object-or-map-keys', note: "`status_distribution` \u2190 `reportStatusDistribution` (reports.go:847) or `reportSnapshotAsOf` | The live path does GROUP BY LOWER(status) per collection; the historical path counts i" },
	"routes/[username]/[workspace]/insights/print/+page.svelte :: each shippedGroups as group (group.collection)": { reason: 'grouped-by-key', note: "`shippedGroups` $derived | Groups are created only when `groups.find(collection)` misses, so each collection appears once." },
	"routes/[username]/[workspace]/insights/print/+page.svelte :: each statusByCollection as group (group.collection)": { reason: 'grouped-by-key', note: "`statusByCollection` $derived | Grouped with `find` on collection." },
	"routes/[username]/[workspace]/library/+page.svelte :: each TABS as tab (tab)": { reason: 'static-literal', note: "two distinct tab names" },
	"routes/[username]/[workspace]/library/+page.svelte :: each categories as category (category.name)": { reason: 'static-literal', note: "`api.library.get` \u2190 static `collections.ConventionLibrary()` | Static literal with five distinct category names (git, quality, pm, docs, build)." },
	"routes/[username]/[workspace]/library/+page.svelte :: each category.conventions as convention (convention.title)": { reason: 'static-literal', note: "same static library | All 18 convention titles are distinct (checked for repeats)." },
	"routes/[username]/[workspace]/library/+page.svelte :: each category.playbooks as playbook (playbook.title)": { reason: 'static-literal', note: "static `PlaybookLibrary()` | Four distinct titles: Ship tasks, Plan a new initiative, Decompose a plan into tasks, Onboard a workspace." },
	"routes/[username]/[workspace]/library/+page.svelte :: each playbookCategories as category (category.name)": { reason: 'static-literal', note: "static `PlaybookLibrary()` | One category, \"agent-workflows\"." },
	"routes/[username]/[workspace]/playbooks/+page.svelte :: each allScopes as s (s)": { reason: 'deduped', note: "schema options via parseSchema, item values deduped against them" },
	"routes/[username]/[workspace]/playbooks/+page.svelte :: each allTriggers as t (t)": { reason: 'deduped', note: "schema options via parseSchema, item values deduped against them" },
	"routes/[username]/[workspace]/playbooks/+page.svelte :: each sorted as item (item.id)": { reason: 'db-primary-key', note: "`sorted` \u2190 `playbooks` \u2190 `api.items.listByCollection` | Item ids are primary keys from one SELECT; the page only replaces or filters this list, never appends to it." },
	"routes/[username]/[workspace]/playbooks/[slug]/+page.svelte :: each storedMismatches as m (m.label)": { reason: 'static-literal', note: "at most one entry per fixed label: Status, Trigger, Scope" },
	"routes/[username]/[workspace]/roles/+page.svelte :: each (laneData[laneKey(lane)] ?? []) as item (item.id)": { reason: 'db-primary-key', note: "items partitioned by their single role column" },
	"routes/[username]/[workspace]/roles/+page.svelte :: each eligibleCollections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list" },
	"routes/[username]/[workspace]/roles/+page.svelte :: each orderedLanes as lane (lane.role?.id ?? '__unassigned')": { reason: 'db-primary-key', note: "`lanes` from `GetRoleBoardItems` (store/agent_roles.go:300) | one lane per role from `ListAgentRoles` (primary key) plus a single unassigned lane; client reorders only permute it" },
	"routes/[username]/[workspace]/settings/+page.svelte :: each collections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list (GROUP BY c.id)" },
	"routes/[username]/[workspace]/settings/+page.svelte :: each contextSummary as entry (entry.label)": { reason: 'static-literal', note: "`contextSummary` $derived (l.903) | at most one push per distinct literal label (Repositories/Commands/Languages/Deployment/Assumptions)." },
	"routes/[username]/[workspace]/settings/+page.svelte :: each invitations as inv (inv.id)": { reason: 'db-primary-key', note: "`memberData.invitations` \u2192 `store.ListWorkspaceInvitations` | single-table SELECT on the `workspace_invitations` id; local edits only filter." },
	"routes/[username]/[workspace]/settings/+page.svelte :: each members as member (member.user_id)": { reason: 'db-primary-key', note: "workspace_members PK (workspace_id, user_id)" },
	"routes/[username]/[workspace]/settings/+page.svelte :: each nonSystemCollections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list (GROUP BY c.id), filtered" },
	"routes/[username]/[workspace]/settings/+page.svelte :: each schema.fields as field (field.key)": { reason: 'deduped', note: "parseSchema" },
	"routes/[username]/[workspace]/settings/+page.svelte :: each systemCollections as coll (coll.id)": { reason: 'db-primary-key', note: "collections list" },
	"routes/[username]/[workspace]/settings/+page.svelte :: each tabs as tab (tab.id)": { reason: 'static-literal', note: "static `allTabs` literal (l.155), filtered | six distinct literal ids (general/members/collections/storage/apps/danger); the filter only removes entries." },
	"routes/[username]/[workspace]/settings/+page.svelte :: each workspaceApps as app (app.id)": { reason: 'db-primary-key', note: "workspace_members PK (one per app user)" },
	"routes/[username]/[workspace]/starred/+page.svelte :: each group.items as item (item.id)": { reason: 'deduped', note: "`starredStore.ordered` \u00d7 localIndex rows | `item_stars` has `PRIMARY KEY(user_id, item_id)`; `withPendingStarsFirst` and `toggle` dedupe the order list (starred.svelte.ts:45/115)" },
	"routes/[username]/[workspace]/starred/+page.svelte :: each groupedItems as group (group.collection.id)": { reason: 'object-or-map-keys', note: "`groupedItems` | Map keyed by `collection_id`, resolved against a primary-key collection list" },
	"routes/[username]/[workspace]/tags/+page.svelte :: each uniqueBy(tags, (x) => x.tag) as t (t.tag)": { reason: 'deduped', note: "the list passes through uniqueBy (TASK-3539)" },
	"routes/[username]/[workspace]/tags/[tag]/+page.svelte :: each group.items as item (item.id)": { reason: 'object-or-map-keys', note: "`localIndex.getAll` | SvelteMap keyed by item id." },
	"routes/[username]/[workspace]/tags/[tag]/+page.svelte :: each group.items as item (item.id) #2": { reason: 'object-or-map-keys', note: "`localIndex.getAll` | SvelteMap keyed by item id." },
	"routes/[username]/[workspace]/tags/[tag]/+page.svelte :: each groupedItems as group (group.collection.id)": { reason: 'object-or-map-keys', note: "`groupedItems` | Map keyed by `collection_id`." },
	"routes/[username]/[workspace]/tags/[tag]/+page.svelte :: each groupedItems as group (group.collection.id) #2": { reason: 'object-or-map-keys', note: "`groupedItems` | Map keyed by `collection_id`." },
	"routes/console/+page.svelte :: each ownedWorkspaces as ws (ws.id)": { reason: 'db-primary-key', note: "`api.workspaces.list` \u2190 `GetUserWorkspaces` (workspace_members.go:661) | `workspace_members` has PRIMARY KEY(workspace_id, user_id) and the query filters to one user." },
	"routes/console/+page.svelte :: each sharedWorkspaces as ws (ws.id)": { reason: 'db-primary-key', note: "GetUserWorkspaces, one per membership" },
	"routes/console/admin/+layout.svelte :: each Object.entries(adminStore.stats.users_by_plan) as [plan, count] (plan)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"routes/console/admin/+layout.svelte :: each tabs as tab (tab.href)": { reason: 'static-literal', note: "static `tabs` literal | Distinct hrefs; the conditional Billing entry is also distinct." },
	"routes/console/admin/+page.svelte :: each users as user (user.id)": { reason: 'deduped', note: "appendUnique on Load more" },
	"routes/console/admin/audit-log/+page.svelte :: each ACTION_TYPES as action (action)": { reason: 'static-literal', note: "24 distinct actions (checked)" },
	"routes/console/admin/audit-log/+page.svelte :: each entries as entry (entry.id)": { reason: 'deduped', note: "activity pages | primary key per page; pages are joined with `appendUnique` (lib/utils/activityPaging.ts:41), which dedupes by id" },
	"routes/console/admin/invitations/+page.svelte :: each invitations as inv (inv.id)": { reason: 'db-primary-key', note: "`ListPendingInvitationsAdmin` (workspace_members.go:1376) | Primary key from a single SELECT; the list is replaced, never appended." },
	"routes/console/admin/mcp-audit/+page.svelte :: each entries as entry (entry.id)": { reason: 'deduped', note: "appendUnique on Load more" },
	"routes/console/admin/settings/+page.svelte :: each LIMIT_FEATURES as feat (feat)": { reason: 'static-literal', note: "distinct feature keys" },
	"routes/console/admin/settings/+page.svelte :: each rd.problems.filter((p) => p !== rd.blocked) as problem (problem)": { reason: 'static-literal', note: "at most one message per configuration variable, each with its own prefix" },
	"routes/console/billing/+page.svelte :: each COMPARE_ROWS as row (row.key)": { reason: 'static-literal', note: "distinct row keys" },
	"routes/console/billing/+page.svelte :: each COMPARE_ROWS as row (row.key) #2": { reason: 'static-literal', note: "distinct row keys" },
	"routes/console/connected-apps/+page.svelte :: each appGrants as grant (grant.id)": { reason: 'db-primary-key', note: "`app_grants` \u2192 `store.ListUserAppGrants` | app_token_bindings.request_id is the PRIMARY KEY; the joins are 1:1 by id." },
	"routes/console/connected-apps/+page.svelte :: each apps as app (app.id)": { reason: 'grouped-by-key', note: "grouped server-side into one entry per request_id" },
	"routes/console/connected-apps/+page.svelte :: each eaWsList as ws (ws)": { reason: 'db-primary-key', note: "oauth_connection_workspaces PK; slugs globally unique" },
	"routes/console/connected-apps/+page.svelte :: each pickable as ws (ws.slug)": { reason: 'db-primary-key', note: "`userWorkspaces` (`api.workspaces.list` \u2192 `store.GetUserWorkspaces`), minus the allow-list | workspaces JOIN workspace_members filtered on one user_id; PK (workspace_id, user_id) p" },
	"routes/console/connected-apps/+page.svelte :: each uniqueStrings(app.redirect_uris ?? []) as uri (uri)": { reason: 'deduped', note: "the list passes through uniqueStrings (TASK-3539)" },
	"routes/console/connected-apps/+page.svelte :: each visibleChips as ws (ws)": { reason: 'db-primary-key', note: "`app.allowed_workspaces` \u2190 oauth_connection_workspaces JOIN workspaces | PRIMARY KEY (request_id, workspace_id) gives one row per workspace, and workspaces.slug is globally `UNIQUE" },
	"routes/console/deleted-workspaces/+page.svelte :: each workspaces as ws (ws.slug)": { reason: 'db-primary-key', note: "workspace slugs are globally unique" },
	"routes/console/settings/+page.svelte :: each linkProviders as p (p.id)": { reason: 'static-literal', note: "github, google, apple" },
	"routes/console/settings/+page.svelte :: each tokens as token (token.id)": { reason: 'db-primary-key', note: "`api.auth.tokens.list` \u2192 `ListUserAPITokens`, plus a local append of a newly created token | single-table SELECT by PK; a create appends a fresh server id only after the load finis" },
	"routes/console/tutorials/+page.svelte :: each uniqueBy(catalog.paths, (p) => p.id) as path (path.id)": { reason: 'deduped', note: "the list passes through uniqueBy (TASK-3539)" },
	"routes/console/tutorials/+page.svelte :: each uniqueBy(tutorials, (x) => x.slug) as t (t.slug)": { reason: 'deduped', note: "the list passes through uniqueBy (TASK-3539)" },
	"routes/s/[token]/+page.svelte :: each BASE_VIEWS as bv (bv.value)": { reason: 'static-literal', note: "three distinct view values" },
	"routes/s/[token]/+page.svelte :: each Object.entries(itemData.fields) as [key, value] (key)": { reason: 'object-or-map-keys', note: "Object.entries keys" },
	"routes/s/[token]/+page.svelte :: each savedViews as sv (sv.slug)": { reason: 'db-primary-key', note: "share payload `collection.views` \u2190 `store.ListViews` (internal/store/views.go:103) | Single SELECT for one collection; `views` has UNIQUE(workspace_id, slug) on both SQLite and Pos" },
};
