package server

import (
	"strings"

	"github.com/PerpetualSoftware/pad/internal/models"
)

// resolveItemCollectionSlug resolves a user-supplied collection slug against
// the workspace's ACTUAL collections, so a regular singular/plural pair works
// for any collection rather than only the seven the client-side alias map
// happens to know (BUG-2578).
//
// "Regular" is the honest scope: only a trailing ASCII `s` is added or
// removed, so `spec`/`specs` resolves and `category`/`categories` does not.
// See collectionSlugCandidates for why that is a deliberate stopping point
// rather than a gap to close with an inflector.
//
// Why this lives on the server. The alias map (collections.NormalizeSlug) is a
// hardcoded switch over the DEFAULT templates' collection names, called from
// the CLI and from the MCP dispatcher — both CLIENT side. It has no view of
// the workspace, so a template-defined or user-created collection like `specs`
// gets no singular form, and `pad item create spec` fails with "Collection not
// found" for a collection that plainly exists in the caller's own bootstrap
// payload. The workspace's collection list only exists here, so resolving here
// fixes the CLI, the remote MCP transport, the web UI and any direct API
// consumer at once, instead of teaching each client the same trick.
//
// EXACT MATCH ALWAYS WINS. The fallbacks run only when the input names no
// collection at all, so this can never redirect a request that would otherwise
// have succeeded — which is the property that makes it safe to add underneath
// existing callers. (The client-side map does NOT have this property: it
// rewrites before the server sees the input, so it can shadow a real
// collection. That is BUG-2630, a separate defect this does not fix.)
//
// Scope is deliberate: item-facing entry points only — create, list, move and
// bulk move, the surfaces the bug is about. In particular this is NOT wired
// into store.GetCollectionBySlug, which has 23 call sites including
// authorization paths (authz_cross_workspace, handlers_grants,
// handlers_share_links). Fuzzy resolution inside a function used for
// permission checks is how a check and the action it guards come to disagree
// about which collection they mean.
//
// Returns (nil, nil) when nothing matches, exactly as GetCollectionBySlug
// does, so callers keep their existing not-found handling.
func (s *Server) resolveItemCollectionSlug(workspaceID, input string) (*models.Collection, error) {
	coll, err := s.store.GetCollectionBySlug(workspaceID, input)
	if err != nil || coll != nil {
		return coll, err
	}

	// An ARCHIVED collection still CLAIMS its name. GetCollectionBySlug skips
	// soft-deleted rows, so without this an archived `spec` alongside a live
	// `specs` would let `spec` fall through to `specs` — quietly redirecting
	// writes the caller aimed at a name that does exist, just not in a
	// writable state. Refusing is the same call made against the client-side
	// alias map in BUG-2630: a silent misroute into a different collection is
	// worse than an honest not-found, and here it also survives a later
	// restore, which would otherwise leave items stranded in the collection
	// they were rerouted to (codex round 7).
	archived, err := s.store.ArchivedCollectionClaimsSlug(workspaceID, input)
	if err != nil {
		return nil, err
	}
	if archived {
		return nil, nil
	}

	for _, candidate := range collectionSlugCandidates(input) {
		coll, err := s.store.GetCollectionBySlug(workspaceID, candidate)
		if err != nil || coll != nil {
			return coll, err
		}
	}
	return nil, nil
}

// collectionSlugCandidates returns the alternative slugs to try when `input`
// matched nothing, in priority order and never including `input` itself.
//
// Only ASCII-`s` pluralization is attempted. That is not a limitation to fix
// by reaching for an inflector: collection slugs are generated by slugify and
// the plural convention is the house style, so `s` covers the real cases,
// while irregular-plural guessing ("person" -> "people") would start inventing
// mappings a user never wrote. Anything an inflector would catch, an exact
// slug still resolves.
func collectionSlugCandidates(input string) []string {
	trimmed := strings.ToLower(strings.TrimSpace(input))
	if trimmed == "" {
		return nil
	}

	var out []string
	// A case-only difference comes FIRST. `Spec` names the collection `spec`
	// more closely than it names `specs`, so trying pluralization ahead of the
	// folded form would resolve `Spec` to `specs` in a workspace holding both
	// — the same misfiling the exact-match rule exists to prevent, reached by
	// a different route (codex round 3 P1).
	if trimmed != input {
		out = append(out, trimmed)
	}
	// Singular -> plural: the reported case (`spec` -> `specs`).
	out = append(out, trimmed+"s")
	// Plural -> singular, for a collection whose slug is genuinely singular
	// (`pad item create tasks` in a workspace whose collection is `task`).
	if s := strings.TrimSuffix(trimmed, "s"); s != trimmed && s != "" {
		out = append(out, s)
	}
	return out
}
