package cli

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// TestGenerateLegacySkillHashes regenerates skill_legacy_hashes.go: the hash
// of every skill text a pad release wrote, per output format, before skill
// files carried a stamp (BUG-3466). Run it, after tagging any release that
// still wrote unstamped files, with
//
//	GEN_SKILL_HASHES=1 go test ./internal/cli/ -run TestGenerateLegacySkillHashes
//
// It reads each tag's skills/pad/SKILL.md and internal/cli/agents.go with
// `git show`, so it needs the release tags, and it rebuilds each format the
// way that tag's FormatForTool did: claude verbatim, copilot and the plain
// body from StripFrontmatter (unchanged in every tag), and agents from the
// shared frontmatter plus either the stripped skill or, from v0.17.0, the
// tag's agentsSkillBody constant. The working tree's own output is included
// too, so the copies this release's predecessors wrote are all covered.
func TestGenerateLegacySkillHashes(t *testing.T) {
	if os.Getenv("GEN_SKILL_HASHES") == "" {
		t.Skip("generator; run with GEN_SKILL_HASHES=1")
	}
	sets := map[string]map[string]bool{"claude": {}, "agents": {}, "copilot": {}, "body": {}}
	add := func(skill []byte, agentsBody string) {
		sets["claude"][skillHash(skill)] = true
		stripped := StripFrontmatter(skill)
		sets["copilot"][skillHash(append([]byte(copilotFrontmatter), stripped...))] = true
		sets["body"][skillHash(stripped)] = true
		if agentsBody != "" {
			sets["agents"][skillHash([]byte(agentsFrontmatter+agentsBody))] = true
		} else {
			sets["agents"][skillHash(append([]byte(agentsFrontmatter), stripped...))] = true
		}
	}

	tags, err := exec.Command("git", "tag", "--list", "v*").Output()
	if err != nil {
		t.Fatalf("git tag: %v", err)
	}
	n := 0
	for _, tag := range strings.Fields(string(tags)) {
		skill, err := exec.Command("git", "show", tag+":skills/pad/SKILL.md").Output()
		if err != nil {
			continue // a tag from before the skill existed
		}
		src, err := exec.Command("git", "show", tag+":internal/cli/agents.go").Output()
		if err != nil {
			t.Fatalf("%s agents.go: %v", tag, err)
		}
		body, err := stringConst(src, "agentsSkillBody")
		if err != nil {
			t.Fatalf("%s: %v", tag, err)
		}
		add(skill, body)
		n++
	}
	head, err := os.ReadFile("../../skills/pad/SKILL.md")
	if err != nil {
		t.Fatal(err)
	}
	add(head, agentsSkillBody)

	var b strings.Builder
	b.WriteString("// Code generated by TestGenerateLegacySkillHashes; DO NOT EDIT.\n\npackage cli\n\n")
	b.WriteString("// legacySkillHashes is what pad releases wrote, per output format, before\n")
	b.WriteString("// skill files carried a stamp (BUG-3466). Frozen: see skillstamp.go.\n")
	b.WriteString("var legacySkillHashes = map[string]map[string]bool{\n")
	for _, f := range []string{"agents", "body", "claude", "copilot"} {
		hs := make([]string, 0, len(sets[f]))
		for h := range sets[f] {
			hs = append(hs, h)
		}
		sort.Strings(hs)
		fmt.Fprintf(&b, "\t%q: {\n", f)
		for _, h := range hs {
			fmt.Fprintf(&b, "\t\t%q: true,\n", h)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	if err := os.WriteFile("skill_legacy_hashes.go", []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("%d tags; agents %d, body %d, claude %d, copilot %d", n, len(sets["agents"]), len(sets["body"]), len(sets["claude"]), len(sets["copilot"]))
}

// stringConst evaluates a string constant declared in Go source as literals
// joined by +. "" when the file declares no such constant.
func stringConst(src []byte, name string) (string, error) {
	f, err := parser.ParseFile(token.NewFileSet(), "agents.go", src, 0)
	if err != nil {
		return "", err
	}
	for _, d := range f.Decls {
		g, ok := d.(*ast.GenDecl)
		if !ok || g.Tok != token.CONST {
			continue
		}
		for _, s := range g.Specs {
			vs := s.(*ast.ValueSpec)
			for i, id := range vs.Names {
				if id.Name == name {
					return evalString(vs.Values[i])
				}
			}
		}
	}
	return "", nil
}

func evalString(e ast.Expr) (string, error) {
	switch x := e.(type) {
	case *ast.BasicLit:
		if x.Kind != token.STRING {
			return "", fmt.Errorf("non-string literal")
		}
		return strconv.Unquote(x.Value)
	case *ast.BinaryExpr:
		if x.Op != token.ADD {
			return "", fmt.Errorf("unexpected operator %s", x.Op)
		}
		l, err := evalString(x.X)
		if err != nil {
			return "", err
		}
		r, err := evalString(x.Y)
		return l + r, err
	case *ast.ParenExpr:
		return evalString(x.X)
	}
	return "", fmt.Errorf("unexpected expression %T", e)
}
