package cli

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// TestGenerateLegacySkillHashes regenerates skill_legacy_hashes.go: the hash
// of every skill text a pad release wrote, per output format, before skill
// files carried a stamp (BUG-3466). Run it, after tagging any release that
// still wrote unstamped files, with
//
//	GEN_SKILL_HASHES=1 go test ./internal/cli/ -run TestGenerateLegacySkillHashes
//
// It reads each tag's skills/pad/SKILL.md and internal/cli/agents.go with
// `git show`, so it needs the release tags, and it rebuilds each format the
// way that tag's FormatForTool did: claude verbatim, copilot and the plain
// body from StripFrontmatter (unchanged in every tag), and agents from the
// shared frontmatter plus either the stripped skill or, from v0.17.0, the
// tag's agentsSkillBody constant. RELEASED output only (codex r3): the
// working tree's text was never shipped, so it is never trusted as pad's;
// a file a dev build wrote after the last tag is kept, and --force replaces
// it. Regenerate after tagging any release that still wrote unstamped files.
func TestGenerateLegacySkillHashes(t *testing.T) {
	if os.Getenv("GEN_SKILL_HASHES") == "" {
		t.Skip("generator; run with GEN_SKILL_HASHES=1")
	}
	sets := map[string]map[string]bool{"claude": {}, "agents": {}, "copilot": {}, "body": {}}
	tags := unstampedReleaseTags(t)
	for _, tag := range tags {
		for f, out := range releasedSkillOutputs(t, tag) {
			sets[f][skillHash(out)] = true
		}
	}
	n := len(tags)
	var b strings.Builder
	b.WriteString("// Code generated by TestGenerateLegacySkillHashes; DO NOT EDIT.\n\npackage cli\n\n")
	b.WriteString("// legacySkillHashes is what pad releases wrote, per output format, before\n")
	b.WriteString("// skill files carried a stamp (BUG-3466). Frozen: see skillstamp.go.\n")
	b.WriteString("var legacySkillHashes = map[string]map[string]bool{\n")
	for _, f := range []string{"agents", "body", "claude", "copilot"} {
		hs := make([]string, 0, len(sets[f]))
		for h := range sets[f] {
			hs = append(hs, h)
		}
		sort.Strings(hs)
		fmt.Fprintf(&b, "\t%q: {\n", f)
		for _, h := range hs {
			fmt.Fprintf(&b, "\t\t%q: true,\n", h)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	if err := os.WriteFile("skill_legacy_hashes.go", []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("%d tags; agents %d, body %d, claude %d, copilot %d", n, len(sets["agents"]), len(sets["body"]), len(sets["claude"]), len(sets["copilot"]))
}

// unstampedReleaseTags lists the release tags that wrote skill files without
// a stamp: every v* tag that has a skill but not internal/cli/skillstamp.go.
// Empty when the checkout has no tags.
func unstampedReleaseTags(t *testing.T) []string {
	t.Helper()
	out, err := exec.Command("git", "tag", "--list", "v*").Output()
	if err != nil {
		return nil
	}
	var tags []string
	for _, tag := range strings.Fields(string(out)) {
		if exec.Command("git", "cat-file", "-e", tag+":skills/pad/SKILL.md").Run() != nil {
			continue // a tag from before the skill existed
		}
		if exec.Command("git", "cat-file", "-e", tag+":internal/cli/skillstamp.go").Run() == nil {
			continue // stamped: its files carry their own marker
		}
		tags = append(tags, tag)
	}
	return tags
}

// releasedSkillOutputs rebuilds what tag's pad wrote, per output format.
func releasedSkillOutputs(t *testing.T, tag string) map[string][]byte {
	t.Helper()
	skill, err := exec.Command("git", "show", tag+":skills/pad/SKILL.md").Output()
	if err != nil {
		t.Fatalf("%s SKILL.md: %v", tag, err)
	}
	src, err := exec.Command("git", "show", tag+":internal/cli/agents.go").Output()
	if err != nil {
		t.Fatalf("%s agents.go: %v", tag, err)
	}
	agentsBody, err := stringConst(src, "agentsSkillBody")
	if err != nil {
		t.Fatalf("%s: %v", tag, err)
	}
	stripped := StripFrontmatter(skill)
	out := map[string][]byte{
		"claude":  skill,
		"copilot": append([]byte(copilotFrontmatter), stripped...),
		"body":    stripped,
		"agents":  append([]byte(agentsFrontmatter), stripped...),
	}
	if agentsBody != "" {
		out["agents"] = []byte(agentsFrontmatter + agentsBody)
	}
	return out
}

// Every unstamped release's output is in the frozen list, so a release cut
// before the list was regenerated fails here, loudly, rather than its users'
// unedited skills reading as edited (lead, BUG-3466). Needs the release tags:
// CI's shallow clone has none and skips; the release workflow fetches them
// (fetch-depth: 0) and runs this before it publishes.
func TestLegacySkillHashesCoverEveryUnstampedRelease(t *testing.T) {
	tags := unstampedReleaseTags(t)
	if len(tags) == 0 {
		t.Skip("no release tags in this checkout; the release workflow, which fetches them, runs this")
	}
	for _, tag := range tags {
		for f, out := range releasedSkillOutputs(t, tag) {
			if !legacySkillHashes[f][skillHash(out)] {
				t.Errorf("%s's %s skill is not in skill_legacy_hashes.go; run GEN_SKILL_HASHES=1 go test ./internal/cli/ -run TestGenerateLegacySkillHashes", tag, f)
			}
		}
	}
}

// stringConst evaluates a string constant declared in Go source as literals
// joined by +. "" when the file declares no such constant.
func stringConst(src []byte, name string) (string, error) {
	f, err := parser.ParseFile(token.NewFileSet(), "agents.go", src, 0)
	if err != nil {
		return "", err
	}
	for _, d := range f.Decls {
		g, ok := d.(*ast.GenDecl)
		if !ok || g.Tok != token.CONST {
			continue
		}
		for _, s := range g.Specs {
			vs := s.(*ast.ValueSpec)
			for i, id := range vs.Names {
				if id.Name == name {
					return evalString(vs.Values[i])
				}
			}
		}
	}
	return "", nil
}

func evalString(e ast.Expr) (string, error) {
	switch x := e.(type) {
	case *ast.BasicLit:
		if x.Kind != token.STRING {
			return "", fmt.Errorf("non-string literal")
		}
		return strconv.Unquote(x.Value)
	case *ast.BinaryExpr:
		if x.Op != token.ADD {
			return "", fmt.Errorf("unexpected operator %s", x.Op)
		}
		l, err := evalString(x.X)
		if err != nil {
			return "", err
		}
		r, err := evalString(x.Y)
		return l + r, err
	case *ast.ParenExpr:
		return evalString(x.X)
	}
	return "", fmt.Errorf("unexpected expression %T", e)
}
