package store

import (
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/PerpetualSoftware/pad/internal/models"
)

// WorkspaceStorageInfo is the consolidated quota summary for a workspace:
// used bytes (from the attachments table), the effective limit for the
// owner's plan (after override + platform-setting + hardcoded fallback),
// the plan name, and whether the owner has a per-user storage_bytes
// override configured. -1 in LimitBytes means unlimited.
//
// The override_active flag tracks whether the workspace owner's
// PlanOverrides JSON contains a storage_bytes key — independent of
// whether that override actually changes the effective limit. (On
// pro/self-hosted plans the limit is unlimited regardless; the flag
// still surfaces the admin's intent in the Settings → Storage UI.)
type WorkspaceStorageInfo struct {
	UsedBytes      int64  `json:"used_bytes"`
	LimitBytes     int64  `json:"limit_bytes"` // -1 = unlimited
	Plan           string `json:"plan"`
	OverrideActive bool   `json:"override_active"`
}

// attachmentColumns is the canonical column list. Keep the column names in
// alignment with migrations/047_attachments.sql + pgmigrations/026_attachments.sql.
const attachmentColumns = `id, workspace_id, item_id, uploaded_by, storage_key, content_hash,
	mime_type, size_bytes, filename, width, height, parent_id, variant, created_at, deleted_at`

// scanAttachment scans a single row into a models.Attachment, handling
// nullables via *string / *int.
func scanAttachment(row interface {
	Scan(dest ...any) error
}) (*models.Attachment, error) {
	var a models.Attachment
	var itemID, parentID, variant, deletedAt *string
	var width, height *int
	var createdAt string

	err := row.Scan(
		&a.ID, &a.WorkspaceID, &itemID, &a.UploadedBy, &a.StorageKey, &a.ContentHash,
		&a.MimeType, &a.SizeBytes, &a.Filename, &width, &height,
		&parentID, &variant, &createdAt, &deletedAt,
	)
	if err != nil {
		return nil, err
	}
	a.ItemID = itemID
	a.ParentID = parentID
	a.Variant = variant
	a.Width = width
	a.Height = height
	a.CreatedAt = parseTime(createdAt)
	a.DeletedAt = parseTimePtr(deletedAt)
	return &a, nil
}

// CreateAttachment inserts an attachment row. id and created_at are
// generated by the store. The caller is expected to have already written
// the blob via AttachmentStore.Put — store-level code does not touch the
// filesystem.
func (s *Store) CreateAttachment(a *models.Attachment) error {
	if a.ID == "" {
		a.ID = newID()
	}
	ts := now()
	if a.CreatedAt.IsZero() {
		a.CreatedAt = parseTime(ts)
	} else {
		ts = a.CreatedAt.UTC().Format("2006-01-02T15:04:05Z07:00")
	}

	_, err := s.db.Exec(s.q(`
		INSERT INTO attachments (`+attachmentColumns+`)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	`),
		a.ID, a.WorkspaceID, a.ItemID, a.UploadedBy, a.StorageKey, a.ContentHash,
		a.MimeType, a.SizeBytes, a.Filename, a.Width, a.Height,
		a.ParentID, a.Variant, ts, nil,
	)
	if err != nil {
		return fmt.Errorf("create attachment: %w", err)
	}
	return nil
}

// GetAttachment returns the attachment with the given id, or (nil, nil)
// if no such row exists. Soft-deleted rows ARE returned (so download
// handlers can distinguish "deleted" from "never existed" and return a
// 410 instead of a 404 if they want to in the future); callers that
// want only live rows should check a.DeletedAt.
func (s *Store) GetAttachment(id string) (*models.Attachment, error) {
	a, err := scanAttachment(s.db.QueryRow(s.q(`
		SELECT `+attachmentColumns+` FROM attachments WHERE id = ?
	`), id))
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("get attachment: %w", err)
	}
	return a, nil
}

// GetAttachmentVariant returns the derived attachment row for parentID
// with the given variant key (e.g. "thumb-sm"), or (nil, nil) if no such
// row exists. Used by the download handler when a client passes
// ?variant=thumb-sm — TASK-878 will populate these rows; TASK-872
// implements the lookup so the handler degrades gracefully when no
// thumbnail exists yet.
func (s *Store) GetAttachmentVariant(parentID, variant string) (*models.Attachment, error) {
	a, err := scanAttachment(s.db.QueryRow(s.q(`
		SELECT `+attachmentColumns+` FROM attachments
		WHERE parent_id = ? AND variant = ? AND deleted_at IS NULL
		LIMIT 1
	`), parentID, variant))
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("get attachment variant: %w", err)
	}
	return a, nil
}

// WorkspaceStorageUsage returns the total bytes consumed by non-deleted
// attachments in the workspace. Includes derived blobs (thumbnails) —
// those are real bytes on disk and count against quota.
func (s *Store) WorkspaceStorageUsage(workspaceID string) (int64, error) {
	var total sql.NullInt64
	err := s.db.QueryRow(s.q(`
		SELECT COALESCE(SUM(size_bytes), 0)
		FROM attachments
		WHERE workspace_id = ? AND deleted_at IS NULL
	`), workspaceID).Scan(&total)
	if err != nil {
		return 0, fmt.Errorf("workspace storage usage: %w", err)
	}
	return total.Int64, nil
}

// WorkspaceStorageLimit returns the effective storage limit (bytes) for
// the workspace owner's plan, or -1 if the plan is unlimited. Thin
// wrapper around WorkspaceStorageInfo for the upload-time quota check
// path that doesn't care about used bytes / plan / override metadata.
//
// Resolution matches the CheckLimit three-tier order:
//  1. Per-user override (user.PlanOverrides JSON, key "storage_bytes")
//  2. Platform setting (plan_limits_<plan>_storage_bytes)
//  3. Hardcoded fallback (DefaultFreeLimits / DefaultProLimits)
//
// CheckLimit itself can't be reused here because its featureCount path
// only knows about row-counted features (items, members, webhooks, …) —
// storage_bytes is byte-counted via WorkspaceStorageUsage.
func (s *Store) WorkspaceStorageLimit(workspaceID string) (int64, error) {
	info, err := s.WorkspaceStorageInfo(workspaceID)
	if err != nil {
		return 0, err
	}
	return info.LimitBytes, nil
}

// WorkspaceStorageInfo returns the consolidated quota summary for a
// workspace (used + limit + plan + override flag) in a single call.
// Used by the storage usage API (TASK-881) and the Settings → Storage
// page (TASK-882) so the UI can render the usage bar and the
// "(override)" badge from one fetch.
//
// Limit resolution mirrors WorkspaceStorageLimit; pro and self-hosted
// plans return -1 (unlimited) in Phase 1. Workspaces with no owner
// (fresh install, deleted owner) also resolve to unlimited rather than
// blocking uploads.
func (s *Store) WorkspaceStorageInfo(workspaceID string) (*WorkspaceStorageInfo, error) {
	used, err := s.WorkspaceStorageUsage(workspaceID)
	if err != nil {
		return nil, err
	}

	info := &WorkspaceStorageInfo{
		UsedBytes:  used,
		LimitBytes: -1, // default: no enforceable limit (no owner / pro / self-hosted)
	}

	var ownerID sql.NullString
	err = s.db.QueryRow(s.q(`SELECT owner_id FROM workspaces WHERE id = ?`), workspaceID).Scan(&ownerID)
	if err == sql.ErrNoRows {
		return info, nil
	}
	if err != nil {
		return nil, fmt.Errorf("workspace storage info: get owner: %w", err)
	}
	// Workspaces created on a fresh install (no users yet) and legacy
	// workspaces from before owner_id was added have no owner. In both
	// cases there is no plan to consult — treat as unlimited rather
	// than rejecting uploads.
	if !ownerID.Valid || ownerID.String == "" {
		return info, nil
	}
	user, err := s.GetUser(ownerID.String)
	if err != nil {
		return nil, fmt.Errorf("workspace storage info: get user: %w", err)
	}
	if user == nil {
		// Owner row was deleted but the workspace still references it.
		return info, nil
	}

	plan := user.Plan
	if plan == "" {
		plan = "free"
	}
	info.Plan = plan

	// Detect whether a per-user storage_bytes override is configured.
	// We surface this as a flag for the UI even when the plan is
	// pro/self-hosted (where the override has no effect on the
	// effective limit) so admins can see the configured value.
	if user.PlanOverrides != "" {
		var overrides map[string]int
		if err := json.Unmarshal([]byte(user.PlanOverrides), &overrides); err == nil {
			if _, ok := overrides["storage_bytes"]; ok {
				info.OverrideActive = true
			}
		}
	}

	// Pro and self-hosted have no enforced limit in Phase 1.
	if plan == "pro" || plan == "self-hosted" {
		return info, nil
	}

	// resolveLimit returns int (32-bit on 32-bit platforms) so we can't
	// store a quota larger than 2 GiB on 32-bit hosts via this path.
	// That's a non-issue for Phase 1: hardcoded free=500MB, pro=10GB,
	// and 32-bit production hosts are not a supported deployment target
	// for Pad Cloud. If a future plan-tier ever exceeds INT_MAX bytes
	// we'll widen resolveLimit.
	info.LimitBytes = int64(s.resolveLimit(plan, "storage_bytes", user.PlanOverrides))
	return info, nil
}
